gem 'berkshelf',  '~> 3.0'
gem 'chef',       '~> 12.0'
gem 'chefspec',   '4.2.0'
gem 'foodcritic', '~> 4.0'
gem 'kitchen-vagrant'
gem 'knife-spork', '= 1.3.3'
gem 'rake'
gem 'rubocop', ' =0.24.0'
gem 'serverspec'
gem 'test-kitchen', '~> 1.2'
